#Workflow name
name: CI/CD Pipeline

#When the workflow run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#global env's
env:
  NODE_VERSION: '20'

# Jobs to execute
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    #Download source code from the repo
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    #Install deps
    - name: Install dependencies
      run: npm ci

    #Execute linter
    - name: Run Linting
      run: npm run lint
      continue-on-error: false
    
    - name: Run tests
      run: npm test

    #Generate test coverage
    - name: Generate coverage report
      run: npm run test:coverage
      continue-on-error: true

  #Build (executes after tests)
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test # Only runs if tests it's successfully
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ NODE_VERSION }}
        cache: 'npm'
      
    - name: Install deps
      uses: npm ci
    
    #Frontend Build
    - name: Build Frontend
      uses: npm run build
    
    #Save build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/
        retention-days: 7
    
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install dependencies
      run: npm ci
      
    # Auditoría de seguridad
    - name: Run security audit
      run: npm audit --audit-level high
